version: '3'
services:
  server:
    image: alpine:3.6
    ports:
      - "5050:5050"
    volumes:
      - "./bin:/opt/local/bin"
    command: /opt/local/bin/linux/server --port 5050 --delay 100
  gw:
    image: alpine:3.6
    ports:
      - "8080:8080"
    depends_on:
      - server
    volumes:
      - "./bin:/opt/local/bin"
    command: /opt/local/bin/linux/gw --host server --port 5050
