version: '3'
services:
  server:
    image: kobaltmusic/grpc-spike:node
    ports:
      - "5050:5050"
    command: node server.js
  gw:
    image: ubuntu
    ports:
      - "8080:8080"
    depends_on:
      - server
    volumes:
      - ./bin/linux/gw:/opt/local/bin/linux/gw
    command: /opt/local/bin/linux/gw --host server --port 5050
